#! /bin/bash
docker run -d \
  -P \
  -p 5858:8585 \
  -p 8000:8000 \
  --name dev \
  --link db:db \
  --link redis:redis \
  -v $HOME/.ssh:/home/developer/.ssh \
  -v $HOME/dev:/home/developer/dev \
  developer/devenv

docker port dev 22
docker-machine ip development

